image:
  name: hashicorp/terraform:latest
  entrypoint: 
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  AWS_ACCESS_KEY_ID: $MY_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $MY_AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: "ap-south-1"
  # Best Practice: Use a variable for your bucket name
  # STATE_BUCKET: "your-terraform-state-bucket-name"
  STATE_BUCKET: $MY_STATE_BUCKET

before_script:
  - terraform --version
  - |
    terraform init \
      -backend-config="bucket=${MY_STATE_BUCKET}" \
      -backend-config="region=${AWS_DEFAULT_REGION}" \
      -backend-config="key=terraform.tfstate" \
      -backend-config="use_lockfile=true"

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script: 
    - terraform plan -out="planfile"
    # Converts binary plan to a readable text file for the browser
    - terraform show -no-color planfile > readable_planfile.txt
  artifacts:
    paths:
      - planfile
      - readable_planfile.txt
    expire_in: 1 day
  # This runs on BOTH dev and master
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "master"

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - terraform apply -input=false "planfile"
    # Captures infrastructure IDs to a readable text file
    - terraform output > infra_details.txt
    - cat infra_details.txt
  artifacts:
    paths:
      - infra_details.txt
  # This ONLY runs on the master branch
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  when: manual

